# Site settings
title: 费海明的个人网站 - 关注编程、主流框架、大数据、区块链、数据结构与算法
name: 费海明的个人网站
url: "http://zhiyuan.github.io"
email: feihaming@gmail.com
description: 费海明的个人网站 - 关注编程、主流框架、大数据、区块链、数据结构与算法 | zhiyuan.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: robin-fei # Github ID
baidushare_id: 89860593 #  百度分享 ID
baidutongji_id: 28cf5fa48a599e39c5cc760931de942f # 百度统计 ID
google-analytics_id: UA-50593531-1  # Google Analytics ID
rss_url: "/feed.xml"  # RSS 订阅 URL
logo_image: "/images/logo.png"  # LOGO 图片地址
# Build settings
plugins: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
 
